{% set version = "2022.1.3" %}

package:
  name: pudb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pudb/pudb-{{ version }}.tar.gz
  sha256: 58e83ada9e19ffe92c1fdc78ae5458ef91aeb892a5b8f0e7379e6fa61e0e664a

build:
  number: 0
  entry_points:
    - pudb = pudb.run:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - urwid >=1.1.1
    - urwid_readline
    - pygments >=2.7.4
    - jedi >=0.18

test:
  requires:
    - pytest-mock
  imports:
    - pudb

  commands:
    - pudb --help
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: https://pypi.org/project/pudb/
  license: MIT
  license_file: LICENSE
  summary: 'A full-screen, console-based Python debugger'
  dev_url: https://github.com/inducer/pudb
  doc_url: https://documen.tician.de/pudb/

extra:
  recipe-maintainers:
    - asmeurer
    - inducer
    - matthiasdiener
