{% set version = "2022.1" %}

package:
  name: pudb
  version: {{ version }}

source:
  fn: pudb-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pudb/pudb-{{ version }}.tar.gz
  sha256: e827a4b489dcad561189535db6677becbf32164b2b44df00786eb2d5e00c587e 

build:
  number: 1
  entry_points:
    - pudb = pudb.run:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - urwid >=1.1.1
    - urwid_readline
    - pygments >=2.7.4
    - jedi >=0.18

test:
  requires:
    - pytest-mock
  imports:
    - pudb

  commands:
    - pudb --help
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: https://pypi.org/project/pudb/
  license: MIT
  license_file: LICENSE
  summary: 'A full-screen, console-based Python debugger'
  dev_url: https://github.com/inducer/pudb
  doc_url: https://documen.tician.de/pudb/ 

extra:
  recipe-maintainers:
    - asmeurer
    - inducer
    - matthiasdiener
