{% set version = "2017.1" %}

package:
  name: pudb
  version: {{ version }}

source:
  fn: pudb-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pudb/pudb-{{ version }}.tar.gz
  sha256: 5b20616853c903561fda06b86a35073bd3d243706e4113eb3f3e51cdf32aa074

build:
  # conda skeleton added this, but I'm unsure why it would be needed.
  # preserve_egg_dir: True
  entry_points:
    - pudb = pudb.run:main
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # Urwid is skipped on Windows
  skip: true  # [win]
requirements:
  build:
    - python
    - setuptools
    - urwid >=1.1.1
    - pygments >=1.0
  run:
    - python
    - setuptools
    - urwid >=1.1.1
    - pygments >=1.0

test:
  imports:
    - pudb

  commands:
    - pudb --help

about:
  home: http://pypi.python.org/pypi/pudb
  license: MIT
  summary: 'A full-screen, console-based Python debugger'

  dev_url: https://github.com/inducer/pudb

extra:
  recipe-maintainers:
    - asmeurer
    - inducer
