{% set version = "2021.1" %}

package:
  name: pudb
  version: {{ version }}

source:
  fn: pudb-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pudb/pudb-{{ version }}.tar.gz
  sha256: 309ee82b45a0ffca0bc4c7f521fd3e357589c764f339bdf9dcabb7ad40692d6e

build:
  # conda skeleton added this, but I'm unsure why it would be needed.
  # preserve_egg_dir: True
  entry_points:
    - pudb = pudb.run:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - urwid >=1.1.1
    - pygments >=2.7.4
    - jedi >=0.18

test:
  requires:
    - pytest-mock
  imports:
    - pudb

  commands:
    - pudb --help
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: http://pypi.python.org/pypi/pudb
  license: MIT
  license_file: LICENSE
  summary: 'A full-screen, console-based Python debugger'

  dev_url: https://github.com/inducer/pudb

extra:
  recipe-maintainers:
    - asmeurer
    - inducer
