travis:
  secure:
    BINSTAR_TOKEN: nVBJ6cheJFb/2nTN4TvRJ7f2dapz9MbgLeTZfhN3BgAC9FSP4eTuA4IFwWaWwo0vbVsLZnLshYwPLvZEcUMIrNky7N2mJe6rpClI0tI8hhGFb8e/BAN1WOKOtx/QB96bRpP9kaN9LJgWGwseQ42sV6y6IduVmvofM01O3v4qMazZPAC5MCsYtRhNa1RAy/lyHMtgg+chqfVD7Xh7386ZCC1V05+S21hinzGAaON395Pwv0q6YXmMPiaKVMPFVkgN0FyFj0ks8cmJQ2IhxjcLugg62KpuZD3txC1WhsLvH7l1kyWRjU7biZLxxoVF7dSjglXfou2WAqH7TTBQMUMkVZwxjvaDy2enunSLT6AuSEHynaFGNw7wHLbxvZwaEtFOidq4ujvrgu9Ni6fLa15lF4Q91n8xLLD4kubgVElCAaAceAwL1qmYs9pNRNnF1w+mD2mZ7ldxhgDI6SEjacyHGqquH8RmyQE2HAD0rr5e2M3wqTQI8rFUyysJptCcSuQYLdM4mVAanT64FYyHakfZwhj9f7BEedLywl9wNdw5k6KEv+O7W2dWL8HQj9F+Rt+v6aj/8coBQXlK4QWvCnjal56xKOK9R69J5IKd/Z8u/I5AywF1W7fl5vAkzopnCzYQ9WVekXqKKszBhTK3YcclP7H99eiX3dbR9jiewvrXxH8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
