appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: O0itG29sZgrKYHKQQ0U+qG+rALCL+n6796N+OgXC3svKUYCeFsp3GA8s4OKZhTfaY8Z1n5wKvLKKjwcxm96h+Wnn1DnYSyzj29MhKldYHH+aOM3bB0ba4O+yPTBQHaEmn5PfrgaIsJjRmG3Ko1Y3aFHcKPwZdL8RMEiCk+l/m44VcECYJKWnd0gXBhB0Czi4Mq4nza9oDlzVS/qLw4HY/+fn5WIjXfSBhzRmOMRkK9lR/TNIifbZTw7/yzb/Vcx2iipVK7/fsZLVB/zRpOTTDjS0lAOtBrt+2zDY1nZ0ovgmGYgS9QA/J1/8CUIyBcMhqHSft4aIftwji65PooiCqOv8gHZF9zPpeWfZQxCK62e0kommEUu3GZFkp+HAuB8v95pIlNBtjt/z4hvucXkBtbuuPg0lxjQEJJfUKHcRLHbSZ6BIhR+sJeeyOoFENRg5JypsuuWP71eca+YyaeSp+OHOkSvCjbyh5xRiIareK7C5XwrOa8HbnsiI87zszcEUkFkK92zgtup93x9DdK9d6jrmwLoL4fuaNrZ7yA21vl3bqOFQKzW3pn7aVzX6PR+Ta9pRPYWXjhvwa9H5pfaweMrQi4qes3k5v1RPoIk8urgXu2AkC6X3JTmWrRzMjlN5acjd74KbQyQkKfmqYveMbvwnDVyRKCrxAfiJw//08Os=}
