travis:
  secure:
    BINSTAR_TOKEN: oIbCU2pEhSTW9+uV1W1ZxjCeGCBup4hEWDVmmA/L35JYXChphnR3JxOeOT/R+4hZyKDaxe/WAZIChlZwk5sczjUXI6AlzxfrAQ+5y34aNYWA+DDSLr9L+gUOnCf5rOQp8sqDrwupAe3VVelIy7zeRZ0UAaU2aSeiFBAQdPRYriXsMLX1SkvXEhlUJ58JObmJgdSDeTSk/KK1hDQOcJFcfv0bARLkqmtdo+W9H52m5YT/zDTtibhfISmnbgg67cFITJlugKh154GZaokICgU6xTc8+pkLzOYsFzxn5aZxbJYhgEn38Nknr0qTxe096hgK4CYxG1nV9PkRMlgPgUpnx1+NgKBEZxIJSezOhwFGVgiq7AKepi6POcy7GBx0J/nwiIEBpkKVAMzhfRg8Vs6jbT2e27BaqX4oW5FgtZ7DxuGQR5zJX5xvAk4FwOVlt/t+1CN40/BXVMSS/z7iEMP2RY9dd1kIj1XGDQj0VGmch36bUIz2gHtOhuQqXOZ0l2Ub0dipWYf7G2KEb8nZa+a96yfADaEQ9G97KQaBTnFahAk7XJqzucya29ZslZ8A2KfGpL36gJcmRg+lRsOtj7nfPflTq+zxQ/JGh+SLBUZdmvLjFdzR5qg/FWh4LbAYBXD/PzwlmRdxeR8Nu6X9gDZjOzU8DZoRZB/mE3xHutwYnF8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
