travis:
  secure:
    BINSTAR_TOKEN: mNs7gqTSPyILWjfxTKy2DTu84K8dnrqtw1Z6428H6tbOYVGXjYS4NWVEmb9dhQb1qOu3JHkvAs6yGOHn0WIx6QnMe17yVt4sgNtANNLihqksgIRMLXMiHw/ScaJIEG4wxLR8pBJZcyuNnmKwbs1+5YEifdPO1Nb6hkOL2rsmpTOoUf6u1+SxlfPEuwv54kWP8lH3OlvzrAQ2j8t1l1aRThiQpmnZCyTBoGcsWvIjcfLNQKUXpMGYE7TLBaea3RXHcdO28M5DUw9P1ftXPCE6MceIO6IBHVz74YbLSDI51zLtVCXQPNqqxtqmbtSkTb8/V7dsnG70LLTZzYtH1v3inqfwM9oAtnfD9mVLFR/cixp8xVOdQ8wMLvod5lFfeHs7AEaYhLm2Vtq17+u3sEA8f7KgaywVSX8Ggc5D6CTnMUx1jh0gO1dBy+ByKOP3SGTILrwechOziyRiQViwNerGKNGziMOO+00s4Hm+laX8vD/7xZZVQ8w3kmcpJMs7cegO8SVok4JxTEyHIqzNX3pep2tqRn3CNBdeWOMnavledHtGwD7e7fhzmRU659FgaqqfvroMonklWlYY2iFOuAiBfMWjgohMPRNvcI87QNTYkBSJ5n+z8iVf664UItZJnajXaqU7C5TFas72MRqojHXRUB2xxcOtHWBxn2gRL+VbT/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
